version: '3.7'

services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - kong-net

  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    networks:
      - kong-net
    depends_on:
      - kong-database

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
    networks:
      - kong-net
    ports:
      - "8000:8000"   # Porta de proxy HTTP
      - "8443:8443"   # Porta de proxy HTTPS
      - "8001:8001"   # Porta de administração HTTP
      - "8444:8444"   # Porta de administração HTTPS
    depends_on:
      - kong-migrations

volumes:
  kong_data:

networks:
  kong-net:
    driver: bridge